{"$message_type":"diagnostic","message":"linking with `cc` failed: exit status: 1","code":null,"level":"error","spans":[],"children":[{"message":" \"cc\" \"-Wl,-exported_symbols_list\" \"-Wl,/var/folders/3x/p1y4y6457_q0hlyzzn2358r00000gn/T/rustckMn1jU/list\" \"/var/folders/3x/p1y4y6457_q0hlyzzn2358r00000gn/T/rustckMn1jU/symbols.o\" \"<149 object files omitted>\" \"/Users/barel/projects/walmart_initial_scraper/scarper_walmart/target/debug/deps/{libpyo3_async_runtimes-22750f28bb67b24f.rlib,libserde_json-066a02114c2e2567.rlib,libcsv-0352693b17772df9.rlib,libcsv_core-22aa68cd274f9ea7.rlib,libscraper-423f4da30b2de65f.rlib,libego_tree-7dc85b48406a7054.rlib,libselectors-40ae78fb60622a9e.rlib,libfxhash-3a286ea5f0d62f33.rlib,libbyteorder-4ca775338fb021ac.rlib,libservo_arc-6ea327b1a7c0c7c5.rlib,libcssparser-2cf9dd17c9b77e41.rlib,libdtoa_short-680d796b2c4bf1c9.rlib,libdtoa-9c6fe3bed2f27621.rlib,libhtml5ever-6e5decfbf06c4ea1.rlib,libmarkup5ever-74b904344cf35aca.rlib,libstring_cache-59cd200e9cbf2394.rlib,libprecomputed_hash-924b8fd3623bcba6.rlib,libphf-c0e8656fd421eeae.rlib,libphf_shared-695acb9d189031b2.rlib,libsiphasher-df8a73a17f0ba739.rlib,libtendril-e12e50c6aa96d188.rlib,libutf8-d5f77f7048583788.rlib,libfutf-4efb15dabb0b97e5.rlib,libdebug_unreachable-ffebc63f316286a2.rlib,libmac-8c8c0308b00be5c9.rlib,libreqwest-538a18b4bd899953.rlib,librustls_pki_types-f86ed655cb260bfc.rlib,libzeroize-169870e81f88d932.rlib,libhyper_tls-fac635371bbfbb10.rlib,libtokio_native_tls-1de7043acce2dcbe.rlib,libserde_urlencoded-e0b0317d609da005.rlib,libryu-c51959d8b4c6c8b0.rlib,libmime-20cf2e0ad55ce997.rlib,libencoding_rs-cdfdb4bb658adf71.rlib,libserde-e2cf963ed7c34879.rlib,libtower_http-745b72f4a0c6d873.rlib,libiri_string-9b0804e2c8ae546b.rlib,libtower-ceb2db3d49f72ed9.rlib,libtower_layer-c8464d6968d26713.rlib,libnative_tls-6b26a1e9f2ab28c9.rlib,libtempfile-c54a8abdc773d461.rlib,libgetrandom-d1f3c30fa384a8f4.rlib,libfastrand-e101cfb8cb108080.rlib,librustix-de727bf347c637da.rlib,liberrno-fba44b6f19d64fb6.rlib,libsecurity_framework-0b0fc9c3d1783271.rlib,libsecurity_framework_sys-19a7abd20aa2b6b6.rlib,libhyper_util-aee8e853b2dfa78f.rlib,libsystem_configuration-6eba1efbd3adef79.rlib,libbitflags-4c098e591c9c0f22.rlib,libsystem_configuration_sys-edb3d72b6277bd38.rlib,libcore_foundation-f7e69c07e4d07f24.rlib,libcore_foundation_sys-219528d4f8c67722.rlib,libbase64-019bd94199d388a7.rlib,libipnet-1b7d10333a7ebec9.rlib,libtower_service-aa8b8b499319d807.rlib,libhyper-e643c253e1b67ae5.rlib,libwant-d24448dafbf99ec2.rlib,libtry_lock-16e2b12daa17c03e.rlib,libhttparse-5fc015c961d3b73f.rlib,libh2-eeef922e122905fc.rlib,libtracing-ba0cd51d7266f74f.rlib,libtracing_core-78477f3f7a4f37ce.rlib,libindexmap-d92445b615cdaf07.rlib,libequivalent-7140d419c0d05290.rlib,libhashbrown-9709304b19f89d2a.rlib,libatomic_waker-4384bbcbf85bc3af.rlib,libtokio_util-d06f09492e8d5502.rlib,libtokio-9292b89576ee4e68.rlib,libsignal_hook_registry-eb5a849f861b9564.rlib,libsocket2-986df0f8b272fd85.rlib,libmio-219a80b3ecd128fb.rlib,libparking_lot-c324a41e95cd2078.rlib,libparking_lot_core-34bb95036ef97166.rlib,libcfg_if-82f0ba756a8a62c3.rlib,liblock_api-d1c760c34b200a75.rlib,libscopeguard-3e76f4ef5a14b29e.rlib,libhttp_body_util-2cea840ffa4b06a6.rlib,libhttp_body-d6ca7da2406e9a8e.rlib,liblog-eb5b62757c5ccd60.rlib,liburl-030095ff8af760d5.rlib,libidna-345c8d26353eb004.rlib,libutf8_iter-5c633af86a29833e.rlib,libidna_adapter-3c96aaf2585fc37f.rlib,libicu_properties-6d3532ff1749ee86.rlib,libicu_properties_data-918c643f350f9ac2.rlib,libicu_normalizer-9a1dc41d4e057a86.rlib,libsmallvec-7b612d6ab9a02bd6.rlib,libicu_normalizer_data-c4377e7f6a9f15cf.rlib,libicu_collections-dbe2a3b70bb4630f.rlib,libpotential_utf-1ca3d366779eb209.rlib,libicu_provider-46b9c576a7528437.rlib,libicu_locale_core-904f60fdf916f21a.rlib,libtinystr-27f50af00c279ecc.rlib,liblitemap-2087f8285932aeac.rlib,libwriteable-fead8ac332cf69f4.rlib,libzerovec-0c8a0dd26f89381d.rlib,libzerotrie-a2c95800319f4484.rlib,libyoke-d8c6d85b0709981f.rlib,libstable_deref_trait-676afe839591f0c2.rlib,libzerofrom-882ff516fca64a39.rlib,libform_urlencoded-d27b4a615f07cd0b.rlib,libpercent_encoding-c54ff84c3c204cb4.rlib,libhttp-d7e657b3fdf09cd2.rlib,libitoa-5297858abf071527.rlib,libbytes-02008f075e8eeac1.rlib,libfnv-ebca00e6a018067d.rlib,libsync_wrapper-bbe4cf48878f737e.rlib,libfutures-165560648e8e1dce.rlib,libfutures_executor-8981b133fd159399.rlib,libfutures_util-518192db5a72ca42.rlib,libmemchr-05e8c46bfef2cced.rlib,libfutures_io-4c9fd8cfc655ef9d.rlib,libslab-777e6abf3fd51b54.rlib,libfutures_channel-52be3b1a2306e5bb.rlib,libpin_project_lite-b3644ee9bd935317.rlib,libfutures_sink-b8d45d4ec8b02531.rlib,libfutures_task-0782f53b6689b3e6.rlib,libpin_utils-4beda66d06188d5e.rlib,libfutures_core-7e6c58753591bd6a.rlib,libpyo3-375e9e2282314755.rlib,libmemoffset-0df116c752370925.rlib,libonce_cell-b2172437f067147a.rlib,libpyo3_ffi-426628779b4c707c.rlib,liblibc-fecdacdfe19ba452.rlib,libunindent-a790b8d66568aca1.rlib}.rlib\" \"<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,libcfg_if-*,liblibc-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib\" \"-framework\" \"Security\" \"-framework\" \"SystemConfiguration\" \"-framework\" \"CoreFoundation\" \"-liconv\" \"-lSystem\" \"-lc\" \"-lm\" \"-arch\" \"arm64\" \"-mmacosx-version-min=11.0.0\" \"-o\" \"/Users/barel/projects/walmart_initial_scraper/scarper_walmart/target/debug/deps/libscarper_walmart.dylib\" \"-Wl,-dead_strip\" \"-dynamiclib\" \"-nodefaultlibs\"","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"some arguments are omitted. use `--verbose` to show all linker arguments","code":null,"level":"note","spans":[],"children":[],"rendered":null},{"message":"Undefined symbols for architecture arm64:\n  \"_PyBaseObject_Type\", referenced from:\n      _$LT$pyo3..pycell..impl_..PyClassObjectBase$LT$U$GT$$u20$as$u20$pyo3..pycell..impl_..PyClassObjectLayout$LT$T$GT$$GT$::tp_dealloc::h58f733c1b3644e7b in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\n      _$LT$pyo3..types..any..PyAny$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::ha40972b6f4da7e92 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\n      _$LT$pyo3..impl_..pyclass_init..PyNativeTypeInitializer$LT$T$GT$$u20$as$u20$pyo3..impl_..pyclass_init..PyObjectInit$LT$T$GT$$GT$::into_new_object::inner::hb099e5f415b28526 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyBool_Type\", referenced from:\n      pyo3_ffi::object::Py_SIZE::h3e50d0b8bae62670 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyBytes_AsString\", referenced from:\n      pyo3::types::bytes::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..bytes..PyBytes$GT$$GT$::as_bytes::hab26d1477531b9be in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyBytes_Size\", referenced from:\n      pyo3::types::bytes::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..bytes..PyBytes$GT$$GT$::as_bytes::hab26d1477531b9be in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyCMethod_New\", referenced from:\n      pyo3_ffi::methodobject::PyCFunction_NewEx::h211721dd109be8bd in libpyo3-375e9e2282314755.rlib[11](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.08.rcgu.o)\n  \"_PyCallable_Check\", referenced from:\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_positional::hf83ed63e065bd120 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n  \"_PyDict_New\", referenced from:\n      pyo3::types::dict::PyDict::new::hf4835e0731a9002f in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyDict_Next\", referenced from:\n      _$LT$pyo3..types..dict..borrowed_iter..BorrowedDictIter$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h131f40d089f42cbe in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\n  \"_PyDict_SetItem\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..dict..PyDict$GT$$u20$as$u20$pyo3..types..dict..PyDictMethods$GT$::set_item::inner::he7d42348353b3183 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyErr_GetRaisedException\", referenced from:\n      pyo3::err::err_state::PyErrStateNormalized::take::h5b26ab733f0a4ec8 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyErr_GivenExceptionMatches\", referenced from:\n      pyo3::err::PyErr::is_instance::hcb24bea346943e34 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyErr_NewExceptionWithDoc\", referenced from:\n      pyo3::err::PyErr::new_type::h240e013819f30dac in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyErr_Print\", referenced from:\n      pyo3::err::panic_after_error::ha0a84948ac7f2ded in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyErr_PrintEx\", referenced from:\n      pyo3::err::PyErr::print_panic_and_unwind::h501f324e5d9481f8 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n      pyo3::err::PyErr::print::he6b9395a0db4a29e in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n      pyo3::err::PyErr::print_and_set_sys_last_vars::hb65710a52d09fd2f in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyErr_SetObject\", referenced from:\n      pyo3::err::err_state::raise_lazy::hb4d3d7c77409a7ed in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyErr_SetRaisedException\", referenced from:\n      pyo3::err::err_state::PyErrStateInner::restore::hb22675d933e12dc8 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyErr_SetString\", referenced from:\n      pyo3::err::err_state::raise_lazy::hb4d3d7c77409a7ed in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyErr_WriteUnraisable\", referenced from:\n      pyo3::err::PyErr::write_unraisable::h46a01961ce4bb579 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\n      pyo3::err::PyErr::write_unraisable::h5a08721dc0f897e8 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyEval_RestoreThread\", referenced from:\n      _$LT$pyo3..gil..SuspendGIL$u20$as$u20$core..ops..drop..Drop$GT$::drop::he7b69ed3c9018487 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyEval_SaveThread\", referenced from:\n      pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h0d7ae44ba0566832 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n      pyo3::gil::SuspendGIL::new::hd7c2c7b0745b555c in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyExc_AttributeError\", referenced from:\n      _$LT$pyo3..exceptions..PyAttributeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hd04a22cb9b080284 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n      _$LT$pyo3..exceptions..PyAttributeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hd04a22cb9b080284 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyExc_BaseException\", referenced from:\n      _$LT$pyo3..exceptions..PyBaseException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::had20a16fd8cf2ab4 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n      _$LT$pyo3..exceptions..PyBaseException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::had20a16fd8cf2ab4 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyExc_Exception\", referenced from:\n      _$LT$pyo3..exceptions..PyException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hfbc56b9b7f7457de in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\n      _$LT$pyo3..exceptions..PyException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hfbc56b9b7f7457de in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\n  \"_PyExc_ImportError\", referenced from:\n      _$LT$pyo3..exceptions..PyImportError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::haae446dd50976d78 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n      _$LT$pyo3..exceptions..PyImportError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::haae446dd50976d78 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyExc_RuntimeError\", referenced from:\n      _$LT$pyo3..exceptions..PyRuntimeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::h441c713e190b9615 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n      _$LT$pyo3..exceptions..PyRuntimeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::h441c713e190b9615 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyExc_TypeError\", referenced from:\n      _$LT$pyo3..exceptions..PyTypeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hc3c1baf2806fe7ff in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n      _$LT$pyo3..exceptions..PyTypeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hc3c1baf2806fe7ff in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyExc_ValueError\", referenced from:\n      _$LT$pyo3..exceptions..PyValueError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hade8bc0d858b56d5 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n      _$LT$pyo3..exceptions..PyValueError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hade8bc0d858b56d5 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyException_GetCause\", referenced from:\n      pyo3::err::PyErr::cause::h5af97ecd28b34d51 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyException_GetTraceback\", referenced from:\n      pyo3::err::err_state::PyErrStateNormalized::ptraceback::ha8f819f6b0a3d222 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyException_SetCause\", referenced from:\n      pyo3::err::PyErr::set_cause::hdcde295df4cffae9 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyException_SetTraceback\", referenced from:\n      pyo3::err::PyErr::into_value::hbbd93e0180f90010 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\n  \"_PyGILState_Ensure\", referenced from:\n      pyo3_ffi::pystate::PyGILState_Ensure::h7cfbc1d99d882b0c in libpyo3_ffi-426628779b4c707c.rlib[3](pyo3_ffi-426628779b4c707c.pyo3_ffi.c6cb2f2f16cc958c-cgu.0.rcgu.o)\n  \"_PyGILState_Release\", referenced from:\n      _$LT$pyo3..gil..GILGuard$u20$as$u20$core..ops..drop..Drop$GT$::drop::h03718e0199f8a072 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyImport_Import\", referenced from:\n      pyo3::types::module::PyModule::import::h428876db085330e9 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n      pyo3::types::module::PyModule::import::h62f92beebda604ba in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyInterpreterState_Get\", referenced from:\n      pyo3::impl_::pymodule::ModuleDef::make_module::h87dd06e36cadacdd in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\n  \"_PyInterpreterState_GetID\", referenced from:\n      pyo3::impl_::pymodule::ModuleDef::make_module::h87dd06e36cadacdd in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\n  \"_PyList_Append\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..list..PyList$GT$$u20$as$u20$pyo3..types..list..PyListMethods$GT$::append::inner::h5f1b7bde62fca47c in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\n  \"_PyList_New\", referenced from:\n      pyo3::types::list::PyList::empty::h4cff16c1806afbe0 in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\n  \"_PyLong_FromSsize_t\", referenced from:\n      pyo3::impl_::pyclass::get_sequence_item_from_mapping::h5fd5760b757ce863 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n      pyo3::impl_::pyclass::assign_sequence_item_from_mapping::h370cde47975a093d in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyLong_Type\", referenced from:\n      pyo3_ffi::object::Py_SIZE::h3e50d0b8bae62670 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyModule_Create2\", referenced from:\n      pyo3_ffi::modsupport::PyModule_Create::h76bf9d5c1c62bdca in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\n  \"_PyModule_GetNameObject\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..module..PyModule$GT$$u20$as$u20$pyo3..types..module..PyModuleMethods$GT$::name::h3a655db562d9538c in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyObject_CallNoArgs\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::call0::h856ba9bc07df32e7 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::call0::he4c785bc36370486 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyObject_DelItem\", referenced from:\n      pyo3::impl_::pyclass::assign_sequence_item_from_mapping::h370cde47975a093d in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyObject_GC_UnTrack\", referenced from:\n      pyo3::impl_::pyclass::tp_dealloc_with_gc::h0974fb803161e3ac in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\n      pyo3::impl_::pyclass::tp_dealloc_with_gc::h9f029aea5abfcd5d in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\n  \"_PyObject_GenericGetDict\", referenced from:\n      pyo3::pyclass::create_type_object::PyTypeBuilder::finalize_methods_and_properties::h92f6fcde80d35fc2 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyObject_GenericSetDict\", referenced from:\n      pyo3::pyclass::create_type_object::PyTypeBuilder::finalize_methods_and_properties::h92f6fcde80d35fc2 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyObject_GetAttr\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::getattr::inner::hc8a364cc7e4fba7b in libpyo3-375e9e2282314755.rlib[17](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.14.rcgu.o)\n  \"_PyObject_GetItem\", referenced from:\n      pyo3::impl_::pyclass::get_sequence_item_from_mapping::h5fd5760b757ce863 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyObject_IsTrue\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::is_truthy::h3eb6b2ef53e630de in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyObject_Repr\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::repr::h8f6c63a3a4eb9362 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyObject_SetAttr\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::setattr::inner::h0d11756d4a382efc in libpyo3-375e9e2282314755.rlib[17](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.14.rcgu.o)\n  \"_PyObject_SetAttrString\", referenced from:\n      pyo3::impl_::pyclass::lazy_type_object::initialize_tp_dict::h19f6f3e10ec53429 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyObject_SetItem\", referenced from:\n      pyo3::impl_::pyclass::assign_sequence_item_from_mapping::h370cde47975a093d in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyObject_Str\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::str::h612413025069cf2b in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyObject_Vectorcall\", referenced from:\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::call_positional::ha786422730ce9ed1 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\n  \"_PyObject_VectorcallDict\", referenced from:\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::call::hb0b592389481ea1d in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\n  \"_PyObject_VectorcallMethod\", referenced from:\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_method_positional::hd421204216e0b5fa in scarper_walmart.bjccxi4muvy206fyvrw8dkje6.055z5t8.rcgu.o\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::call_method0::had1a3c3fa6d8eb94 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::call_method_positional::h4a2381d96e05200b in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\n  \"_PyThreadState_Get\", referenced from:\n      pyo3_ffi::pystate::PyThreadState_GET::ha57514a52362691e in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\n  \"_PyTraceBack_Print\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..traceback..PyTraceback$GT$$u20$as$u20$pyo3..types..traceback..PyTracebackMethods$GT$::format::h0b47b5874b72feda in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyTuple_New\", referenced from:\n      pyo3::types::tuple::array_into_tuple::h5623574594b94894 in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\n  \"_PyType_FromSpec\", referenced from:\n      pyo3::pyclass::create_type_object::PyTypeBuilder::build::h26b0fb616d96df4f in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyType_GenericAlloc\", referenced from:\n      _$LT$pyo3..impl_..pyclass_init..PyNativeTypeInitializer$LT$T$GT$$u20$as$u20$pyo3..impl_..pyclass_init..PyObjectInit$LT$T$GT$$GT$::into_new_object::inner::hb099e5f415b28526 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\n  \"_PyType_GetName\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..typeobject..PyType$GT$$u20$as$u20$pyo3..types..typeobject..PyTypeMethods$GT$::name::h8b4d7fef4f140a63 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyType_GetQualName\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$pyo3..types..typeobject..PyType$GT$$u20$as$u20$pyo3..types..typeobject..PyTypeMethods$GT$::qualname::had5f691ff7a61a24 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyType_IsSubtype\", referenced from:\n      pyo3_ffi::object::PyObject_TypeCheck::heb33108442e6d7c1 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\n  \"_PyType_Modified\", referenced from:\n      pyo3::impl_::pyclass::lazy_type_object::LazyTypeObjectInner::ensure_init::_$u7b$$u7b$closure$u7d$$u7d$::hda5982015333342a in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyUnicode_AsEncodedString\", referenced from:\n      pyo3::types::string::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..string..PyString$GT$$GT$::to_string_lossy::hd2eb2ac6832afcd7 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyUnicode_AsUTF8AndSize\", referenced from:\n      pyo3::types::string::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..string..PyString$GT$$GT$::to_str::h6f4f3644c77f65e5 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n  \"_PyUnicode_FromStringAndSize\", referenced from:\n      pyo3::types::string::PyString::new::hca6758c4a650a4d3 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n      pyo3::types::string::PyString::intern::h42c68e1948b2c043 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_PyUnicode_InternInPlace\", referenced from:\n      pyo3::types::string::PyString::intern::h42c68e1948b2c043 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_Py_InitializeEx\", referenced from:\n      pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h0d7ae44ba0566832 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"_Py_IsInitialized\", referenced from:\n      pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h0d7ae44ba0566832 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n      pyo3::gil::GILGuard::acquire::_$u7b$$u7b$closure$u7d$$u7d$::hd0cf759560d24ebe in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\n  \"__PyObject_MakeTpCall\", referenced from:\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_positional::hf83ed63e065bd120 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n  \"__Py_CheckFunctionResult\", referenced from:\n      pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_positional::hf83ed63e065bd120 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n  \"__Py_Dealloc\", referenced from:\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h3a18d43ed254150a in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::hfb5bb426077f9103 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h0c4f3a293732b0e5 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h19cd3ec67d32ec44 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h5dc5d240f71b5e21 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h5e677d5c8505e137 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n      _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h7b00fd7bc9be6dc2 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\n      ...\n  \"__Py_NoneStruct\", referenced from:\n      pyo3_ffi::object::Py_None::h93b9782a03a7a4be in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\n      pyo3_ffi::object::Py_None::h5cd436df29059637 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\nld: symbol(s) not found for architecture arm64\nclang: error: linker command failed with exit code 1 (use -v to see invocation)\n","code":null,"level":"note","spans":[],"children":[],"rendered":null}],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m: linking with `cc` failed: exit status: 1\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m|\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m= \u001b[0m\u001b[0m\u001b[1mnote\u001b[0m\u001b[0m:  \"cc\" \"-Wl,-exported_symbols_list\" \"-Wl,/var/folders/3x/p1y4y6457_q0hlyzzn2358r00000gn/T/rustckMn1jU/list\" \"/var/folders/3x/p1y4y6457_q0hlyzzn2358r00000gn/T/rustckMn1jU/symbols.o\" \"<149 object files omitted>\" \"/Users/barel/projects/walmart_initial_scraper/scarper_walmart/target/debug/deps/{libpyo3_async_runtimes-22750f28bb67b24f.rlib,libserde_json-066a02114c2e2567.rlib,libcsv-0352693b17772df9.rlib,libcsv_core-22aa68cd274f9ea7.rlib,libscraper-423f4da30b2de65f.rlib,libego_tree-7dc85b48406a7054.rlib,libselectors-40ae78fb60622a9e.rlib,libfxhash-3a286ea5f0d62f33.rlib,libbyteorder-4ca775338fb021ac.rlib,libservo_arc-6ea327b1a7c0c7c5.rlib,libcssparser-2cf9dd17c9b77e41.rlib,libdtoa_short-680d796b2c4bf1c9.rlib,libdtoa-9c6fe3bed2f27621.rlib,libhtml5ever-6e5decfbf06c4ea1.rlib,libmarkup5ever-74b904344cf35aca.rlib,libstring_cache-59cd200e9cbf2394.rlib,libprecomputed_hash-924b8fd3623bcba6.rlib,libphf-c0e8656fd421eeae.rlib,libphf_shared-695acb9d189031b2.rlib,libsiphasher-df8a73a17f0ba739.rlib,libtendril-e12e50c6aa96d188.rlib,libutf8-d5f77f7048583788.rlib,libfutf-4efb15dabb0b97e5.rlib,libdebug_unreachable-ffebc63f316286a2.rlib,libmac-8c8c0308b00be5c9.rlib,libreqwest-538a18b4bd899953.rlib,librustls_pki_types-f86ed655cb260bfc.rlib,libzeroize-169870e81f88d932.rlib,libhyper_tls-fac635371bbfbb10.rlib,libtokio_native_tls-1de7043acce2dcbe.rlib,libserde_urlencoded-e0b0317d609da005.rlib,libryu-c51959d8b4c6c8b0.rlib,libmime-20cf2e0ad55ce997.rlib,libencoding_rs-cdfdb4bb658adf71.rlib,libserde-e2cf963ed7c34879.rlib,libtower_http-745b72f4a0c6d873.rlib,libiri_string-9b0804e2c8ae546b.rlib,libtower-ceb2db3d49f72ed9.rlib,libtower_layer-c8464d6968d26713.rlib,libnative_tls-6b26a1e9f2ab28c9.rlib,libtempfile-c54a8abdc773d461.rlib,libgetrandom-d1f3c30fa384a8f4.rlib,libfastrand-e101cfb8cb108080.rlib,librustix-de727bf347c637da.rlib,liberrno-fba44b6f19d64fb6.rlib,libsecurity_framework-0b0fc9c3d1783271.rlib,libsecurity_framework_sys-19a7abd20aa2b6b6.rlib,libhyper_util-aee8e853b2dfa78f.rlib,libsystem_configuration-6eba1efbd3adef79.rlib,libbitflags-4c098e591c9c0f22.rlib,libsystem_configuration_sys-edb3d72b6277bd38.rlib,libcore_foundation-f7e69c07e4d07f24.rlib,libcore_foundation_sys-219528d4f8c67722.rlib,libbase64-019bd94199d388a7.rlib,libipnet-1b7d10333a7ebec9.rlib,libtower_service-aa8b8b499319d807.rlib,libhyper-e643c253e1b67ae5.rlib,libwant-d24448dafbf99ec2.rlib,libtry_lock-16e2b12daa17c03e.rlib,libhttparse-5fc015c961d3b73f.rlib,libh2-eeef922e122905fc.rlib,libtracing-ba0cd51d7266f74f.rlib,libtracing_core-78477f3f7a4f37ce.rlib,libindexmap-d92445b615cdaf07.rlib,libequivalent-7140d419c0d05290.rlib,libhashbrown-9709304b19f89d2a.rlib,libatomic_waker-4384bbcbf85bc3af.rlib,libtokio_util-d06f09492e8d5502.rlib,libtokio-9292b89576ee4e68.rlib,libsignal_hook_registry-eb5a849f861b9564.rlib,libsocket2-986df0f8b272fd85.rlib,libmio-219a80b3ecd128fb.rlib,libparking_lot-c324a41e95cd2078.rlib,libparking_lot_core-34bb95036ef97166.rlib,libcfg_if-82f0ba756a8a62c3.rlib,liblock_api-d1c760c34b200a75.rlib,libscopeguard-3e76f4ef5a14b29e.rlib,libhttp_body_util-2cea840ffa4b06a6.rlib,libhttp_body-d6ca7da2406e9a8e.rlib,liblog-eb5b62757c5ccd60.rlib,liburl-030095ff8af760d5.rlib,libidna-345c8d26353eb004.rlib,libutf8_iter-5c633af86a29833e.rlib,libidna_adapter-3c96aaf2585fc37f.rlib,libicu_properties-6d3532ff1749ee86.rlib,libicu_properties_data-918c643f350f9ac2.rlib,libicu_normalizer-9a1dc41d4e057a86.rlib,libsmallvec-7b612d6ab9a02bd6.rlib,libicu_normalizer_data-c4377e7f6a9f15cf.rlib,libicu_collections-dbe2a3b70bb4630f.rlib,libpotential_utf-1ca3d366779eb209.rlib,libicu_provider-46b9c576a7528437.rlib,libicu_locale_core-904f60fdf916f21a.rlib,libtinystr-27f50af00c279ecc.rlib,liblitemap-2087f8285932aeac.rlib,libwriteable-fead8ac332cf69f4.rlib,libzerovec-0c8a0dd26f89381d.rlib,libzerotrie-a2c95800319f4484.rlib,libyoke-d8c6d85b0709981f.rlib,libstable_deref_trait-676afe839591f0c2.rlib,libzerofrom-882ff516fca64a39.rlib,libform_urlencoded-d27b4a615f07cd0b.rlib,libpercent_encoding-c54ff84c3c204cb4.rlib,libhttp-d7e657b3fdf09cd2.rlib,libitoa-5297858abf071527.rlib,libbytes-02008f075e8eeac1.rlib,libfnv-ebca00e6a018067d.rlib,libsync_wrapper-bbe4cf48878f737e.rlib,libfutures-165560648e8e1dce.rlib,libfutures_executor-8981b133fd159399.rlib,libfutures_util-518192db5a72ca42.rlib,libmemchr-05e8c46bfef2cced.rlib,libfutures_io-4c9fd8cfc655ef9d.rlib,libslab-777e6abf3fd51b54.rlib,libfutures_channel-52be3b1a2306e5bb.rlib,libpin_project_lite-b3644ee9bd935317.rlib,libfutures_sink-b8d45d4ec8b02531.rlib,libfutures_task-0782f53b6689b3e6.rlib,libpin_utils-4beda66d06188d5e.rlib,libfutures_core-7e6c58753591bd6a.rlib,libpyo3-375e9e2282314755.rlib,libmemoffset-0df116c752370925.rlib,libonce_cell-b2172437f067147a.rlib,libpyo3_ffi-426628779b4c707c.rlib,liblibc-fecdacdfe19ba452.rlib,libunindent-a790b8d66568aca1.rlib}.rlib\" \"<sysroot>/lib/rustlib/aarch64-apple-darwin/lib/{libstd-*,libpanic_unwind-*,libobject-*,libmemchr-*,libaddr2line-*,libgimli-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libminiz_oxide-*,libadler2-*,libunwind-*,libcfg_if-*,liblibc-*,liballoc-*,librustc_std_workspace_core-*,libcore-*,libcompiler_builtins-*}.rlib\" \"-framework\" \"Security\" \"-framework\" \"SystemConfiguration\" \"-framework\" \"CoreFoundation\" \"-liconv\" \"-lSystem\" \"-lc\" \"-lm\" \"-arch\" \"arm64\" \"-mmacosx-version-min=11.0.0\" \"-o\" \"/Users/barel/projects/walmart_initial_scraper/scarper_walmart/target/debug/deps/libscarper_walmart.dylib\" \"-Wl,-dead_strip\" \"-dynamiclib\" \"-nodefaultlibs\"\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m= \u001b[0m\u001b[0m\u001b[1mnote\u001b[0m\u001b[0m: some arguments are omitted. use `--verbose` to show all linker arguments\u001b[0m\n\u001b[0m  \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m= \u001b[0m\u001b[0m\u001b[1mnote\u001b[0m\u001b[0m: Undefined symbols for architecture arm64:\u001b[0m\n\u001b[0m            \"_PyBaseObject_Type\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..pycell..impl_..PyClassObjectBase$LT$U$GT$$u20$as$u20$pyo3..pycell..impl_..PyClassObjectLayout$LT$T$GT$$GT$::tp_dealloc::h58f733c1b3644e7b in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..types..any..PyAny$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::ha40972b6f4da7e92 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..impl_..pyclass_init..PyNativeTypeInitializer$LT$T$GT$$u20$as$u20$pyo3..impl_..pyclass_init..PyObjectInit$LT$T$GT$$GT$::into_new_object::inner::hb099e5f415b28526 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyBool_Type\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::object::Py_SIZE::h3e50d0b8bae62670 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyBytes_AsString\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::bytes::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..bytes..PyBytes$GT$$GT$::as_bytes::hab26d1477531b9be in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyBytes_Size\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::bytes::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..bytes..PyBytes$GT$$GT$::as_bytes::hab26d1477531b9be in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyCMethod_New\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::methodobject::PyCFunction_NewEx::h211721dd109be8bd in libpyo3-375e9e2282314755.rlib[11](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.08.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyCallable_Check\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_positional::hf83ed63e065bd120 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyDict_New\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::dict::PyDict::new::hf4835e0731a9002f in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyDict_Next\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..types..dict..borrowed_iter..BorrowedDictIter$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h131f40d089f42cbe in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyDict_SetItem\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..dict..PyDict$GT$$u20$as$u20$pyo3..types..dict..PyDictMethods$GT$::set_item::inner::he7d42348353b3183 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_GetRaisedException\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::err_state::PyErrStateNormalized::take::h5b26ab733f0a4ec8 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_GivenExceptionMatches\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::is_instance::hcb24bea346943e34 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_NewExceptionWithDoc\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::new_type::h240e013819f30dac in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_Print\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::panic_after_error::ha0a84948ac7f2ded in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_PrintEx\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::print_panic_and_unwind::h501f324e5d9481f8 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::err::PyErr::print::he6b9395a0db4a29e in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::err::PyErr::print_and_set_sys_last_vars::hb65710a52d09fd2f in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_SetObject\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::err_state::raise_lazy::hb4d3d7c77409a7ed in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_SetRaisedException\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::err_state::PyErrStateInner::restore::hb22675d933e12dc8 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_SetString\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::err_state::raise_lazy::hb4d3d7c77409a7ed in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyErr_WriteUnraisable\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::write_unraisable::h46a01961ce4bb579 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::err::PyErr::write_unraisable::h5a08721dc0f897e8 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyEval_RestoreThread\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..gil..SuspendGIL$u20$as$u20$core..ops..drop..Drop$GT$::drop::he7b69ed3c9018487 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyEval_SaveThread\", referenced from:\u001b[0m\n\u001b[0m                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h0d7ae44ba0566832 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::gil::SuspendGIL::new::hd7c2c7b0745b555c in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_AttributeError\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyAttributeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hd04a22cb9b080284 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyAttributeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hd04a22cb9b080284 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_BaseException\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyBaseException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::had20a16fd8cf2ab4 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyBaseException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::had20a16fd8cf2ab4 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_Exception\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hfbc56b9b7f7457de in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyException$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hfbc56b9b7f7457de in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_ImportError\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyImportError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::haae446dd50976d78 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyImportError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::haae446dd50976d78 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_RuntimeError\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyRuntimeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::h441c713e190b9615 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyRuntimeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::h441c713e190b9615 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_TypeError\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyTypeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hc3c1baf2806fe7ff in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyTypeError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hc3c1baf2806fe7ff in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyExc_ValueError\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyValueError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hade8bc0d858b56d5 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..exceptions..PyValueError$u20$as$u20$pyo3..type_object..PyTypeInfo$GT$::type_object_raw::_$u7b$$u7b$closure$u7d$$u7d$::hade8bc0d858b56d5 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyException_GetCause\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::cause::h5af97ecd28b34d51 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyException_GetTraceback\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::err_state::PyErrStateNormalized::ptraceback::ha8f819f6b0a3d222 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyException_SetCause\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::set_cause::hdcde295df4cffae9 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyException_SetTraceback\", referenced from:\u001b[0m\n\u001b[0m                pyo3::err::PyErr::into_value::hbbd93e0180f90010 in libpyo3-375e9e2282314755.rlib[5](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.02.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyGILState_Ensure\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::pystate::PyGILState_Ensure::h7cfbc1d99d882b0c in libpyo3_ffi-426628779b4c707c.rlib[3](pyo3_ffi-426628779b4c707c.pyo3_ffi.c6cb2f2f16cc958c-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyGILState_Release\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..gil..GILGuard$u20$as$u20$core..ops..drop..Drop$GT$::drop::h03718e0199f8a072 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyImport_Import\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::module::PyModule::import::h428876db085330e9 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::types::module::PyModule::import::h62f92beebda604ba in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyInterpreterState_Get\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pymodule::ModuleDef::make_module::h87dd06e36cadacdd in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyInterpreterState_GetID\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pymodule::ModuleDef::make_module::h87dd06e36cadacdd in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyList_Append\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..list..PyList$GT$$u20$as$u20$pyo3..types..list..PyListMethods$GT$::append::inner::h5f1b7bde62fca47c in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyList_New\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::list::PyList::empty::h4cff16c1806afbe0 in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyLong_FromSsize_t\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::get_sequence_item_from_mapping::h5fd5760b757ce863 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::assign_sequence_item_from_mapping::h370cde47975a093d in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyLong_Type\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::object::Py_SIZE::h3e50d0b8bae62670 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyModule_Create2\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::modsupport::PyModule_Create::h76bf9d5c1c62bdca in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyModule_GetNameObject\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..module..PyModule$GT$$u20$as$u20$pyo3..types..module..PyModuleMethods$GT$::name::h3a655db562d9538c in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_CallNoArgs\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::call0::h856ba9bc07df32e7 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::call0::he4c785bc36370486 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_DelItem\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::assign_sequence_item_from_mapping::h370cde47975a093d in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_GC_UnTrack\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::tp_dealloc_with_gc::h0974fb803161e3ac in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::tp_dealloc_with_gc::h9f029aea5abfcd5d in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_GenericGetDict\", referenced from:\u001b[0m\n\u001b[0m                pyo3::pyclass::create_type_object::PyTypeBuilder::finalize_methods_and_properties::h92f6fcde80d35fc2 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_GenericSetDict\", referenced from:\u001b[0m\n\u001b[0m                pyo3::pyclass::create_type_object::PyTypeBuilder::finalize_methods_and_properties::h92f6fcde80d35fc2 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_GetAttr\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::getattr::inner::hc8a364cc7e4fba7b in libpyo3-375e9e2282314755.rlib[17](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.14.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_GetItem\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::get_sequence_item_from_mapping::h5fd5760b757ce863 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_IsTrue\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::is_truthy::h3eb6b2ef53e630de in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_Repr\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::repr::h8f6c63a3a4eb9362 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_SetAttr\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::setattr::inner::h0d11756d4a382efc in libpyo3-375e9e2282314755.rlib[17](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.14.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_SetAttrString\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::lazy_type_object::initialize_tp_dict::h19f6f3e10ec53429 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_SetItem\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::assign_sequence_item_from_mapping::h370cde47975a093d in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_Str\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::str::h612413025069cf2b in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_Vectorcall\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::call_positional::ha786422730ce9ed1 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_VectorcallDict\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::call::hb0b592389481ea1d in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyObject_VectorcallMethod\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_method_positional::hd421204216e0b5fa in scarper_walmart.bjccxi4muvy206fyvrw8dkje6.055z5t8.rcgu.o\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..any..PyAny$GT$$u20$as$u20$pyo3..types..any..PyAnyMethods$GT$::call_method0::had1a3c3fa6d8eb94 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$T1$C$T2$C$T3$RP$$GT$::call_method_positional::h4a2381d96e05200b in libpyo3_async_runtimes-22750f28bb67b24f.rlib[6](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.3.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyThreadState_Get\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::pystate::PyThreadState_GET::ha57514a52362691e in libpyo3_async_runtimes-22750f28bb67b24f.rlib[4](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.1.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyTraceBack_Print\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..traceback..PyTraceback$GT$$u20$as$u20$pyo3..types..traceback..PyTracebackMethods$GT$::format::h0b47b5874b72feda in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyTuple_New\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::array_into_tuple::h5623574594b94894 in libpyo3-375e9e2282314755.rlib[12](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.09.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyType_FromSpec\", referenced from:\u001b[0m\n\u001b[0m                pyo3::pyclass::create_type_object::PyTypeBuilder::build::h26b0fb616d96df4f in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyType_GenericAlloc\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..impl_..pyclass_init..PyNativeTypeInitializer$LT$T$GT$$u20$as$u20$pyo3..impl_..pyclass_init..PyObjectInit$LT$T$GT$$GT$::into_new_object::inner::hb099e5f415b28526 in libpyo3-375e9e2282314755.rlib[18](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.15.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyType_GetName\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..typeobject..PyType$GT$$u20$as$u20$pyo3..types..typeobject..PyTypeMethods$GT$::name::h8b4d7fef4f140a63 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyType_GetQualName\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$pyo3..types..typeobject..PyType$GT$$u20$as$u20$pyo3..types..typeobject..PyTypeMethods$GT$::qualname::had5f691ff7a61a24 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyType_IsSubtype\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::object::PyObject_TypeCheck::heb33108442e6d7c1 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyType_Modified\", referenced from:\u001b[0m\n\u001b[0m                pyo3::impl_::pyclass::lazy_type_object::LazyTypeObjectInner::ensure_init::_$u7b$$u7b$closure$u7d$$u7d$::hda5982015333342a in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyUnicode_AsEncodedString\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::string::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..string..PyString$GT$$GT$::to_string_lossy::hd2eb2ac6832afcd7 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyUnicode_AsUTF8AndSize\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::string::_$LT$impl$u20$pyo3..instance..Borrowed$LT$pyo3..types..string..PyString$GT$$GT$::to_str::h6f4f3644c77f65e5 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyUnicode_FromStringAndSize\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::string::PyString::new::hca6758c4a650a4d3 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::types::string::PyString::intern::h42c68e1948b2c043 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_PyUnicode_InternInPlace\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::string::PyString::intern::h42c68e1948b2c043 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_Py_InitializeEx\", referenced from:\u001b[0m\n\u001b[0m                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h0d7ae44ba0566832 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"_Py_IsInitialized\", referenced from:\u001b[0m\n\u001b[0m                pyo3::gil::prepare_freethreaded_python::_$u7b$$u7b$closure$u7d$$u7d$::h0d7ae44ba0566832 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m                pyo3::gil::GILGuard::acquire::_$u7b$$u7b$closure$u7d$$u7d$::hd0cf759560d24ebe in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m            \"__PyObject_MakeTpCall\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_positional::hf83ed63e065bd120 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m            \"__Py_CheckFunctionResult\", referenced from:\u001b[0m\n\u001b[0m                pyo3::types::tuple::_$LT$impl$u20$pyo3..call..PyCallArgs$u20$for$u20$$LP$T0$C$$RP$$GT$::call_positional::hf83ed63e065bd120 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m            \"__Py_Dealloc\", referenced from:\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h3a18d43ed254150a in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::hfb5bb426077f9103 in libpyo3_async_runtimes-22750f28bb67b24f.rlib[3](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.0.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h0c4f3a293732b0e5 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h19cd3ec67d32ec44 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h5dc5d240f71b5e21 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h5e677d5c8505e137 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m                _$LT$pyo3..instance..Bound$LT$T$GT$$u20$as$u20$core..ops..drop..Drop$GT$::drop::h7b00fd7bc9be6dc2 in libpyo3-375e9e2282314755.rlib[3](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.00.rcgu.o)\u001b[0m\n\u001b[0m                ...\u001b[0m\n\u001b[0m            \"__Py_NoneStruct\", referenced from:\u001b[0m\n\u001b[0m                pyo3_ffi::object::Py_None::h93b9782a03a7a4be in libpyo3_async_runtimes-22750f28bb67b24f.rlib[5](pyo3_async_runtimes-22750f28bb67b24f.pyo3_async_runtimes.88d366efccf61451-cgu.2.rcgu.o)\u001b[0m\n\u001b[0m                pyo3_ffi::object::Py_None::h5cd436df29059637 in libpyo3-375e9e2282314755.rlib[7](pyo3-375e9e2282314755.pyo3.1adff79495eabfd9-cgu.04.rcgu.o)\u001b[0m\n\u001b[0m          ld: symbol(s) not found for architecture arm64\u001b[0m\n\u001b[0m          clang: error: linker command failed with exit code 1 (use -v to see invocation)\u001b[0m\n\u001b[0m          \u001b[0m\n\n"}
{"$message_type":"diagnostic","message":"aborting due to 1 previous error","code":null,"level":"error","spans":[],"children":[],"rendered":"\u001b[0m\u001b[1m\u001b[38;5;9merror\u001b[0m\u001b[0m\u001b[1m: aborting due to 1 previous error\u001b[0m\n\n"}
